env:
  node: true

extends: 'airbnb-base'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  linebreak-style: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always